services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - backend_data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  backend_data: